name: smoke
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run smoke against prod
        env:
          BASE: https://scaffoldbot-vercel-stub.vercel.app/api
        run: bash scripts/smoke.sh
