name: test
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  jest:
    runs-on: ubuntu-latest
    env:
      BASE: https://scaffoldbot-vercel-stub.vercel.app/api   # 👈 here
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --ci
